### ISSUE TITLE
Адаптированная версия под Windows10

### ISSUE THREAD

**Issue by baur** [Streletz/tasktracker#1]
Добрый день, 
Радует, что продукт развивается /уже 3.0/ Все же ждём вас версию адаптированную версию под Windows10 /точнее Window Server 2016/, не все компании любит Linux

**Comment by baur** [comment]
Ещё лучшее кросс базовую версию имею ввиду mssql, mysql ведь YII поддерживает это из коробки

**Comment by Streletz** [comment]
Здравствуйте!

Спасибо за интерес к проекту!

Если ничего не случится, то вскоре будет уже бета, а затем и финальная версия 3.0.0. В дальнейшем проект также планируется развивать.

Что касается технологического стека. 

Версия 3.0.0 по прежнему будет работать только с MySQL, но в следующих версиях планируется добавление поддержки и других СУБД.

С Windows Server сложностей быть не должно, если всё необходимое правильно развёрнуто и настроено.

Если же возникают какие-то проблемы, Вы можете создать Issue на GitHub и описать в нём суть проблемы, стек, который Вы используете для Windows (WAMP, WIMP, etc), и как её воспроизвести.

Буду рад обратной связи и по мере возможности постараюсь помочь. К сожалению, на данный момент отсутствует возможность обеспечить полноценную техническую поддержку, т.к. проект не только открытый, но и некоммерческий и разрабатывается в свободное от основной работы время. Надеюсь на понимание.
